### PR TITLE
chore: show subtitles for videos in full-screen mode

### PR DESCRIPTION
**Pull request by shafqat-muneer**
[LEARNER-10236](https://2u-internal.atlassian.net/browse/LEARNER-10236): iOS - videos do not show captions when viewed full-screen

In the current implementation, subtitles are displayed only in full-screen mode, whether in landscape or portrait orientation. Subtitles are not shown in non-full-screen mode for two reasons. First, we cannot control the default caption on/off option provided by AVPlayer. Second, in normal mode, users can already view captions in any language, making it unnecessary to display additional subtitles. However, in full-screen mode, the option to view captions is unavailable, which is why we ensure subtitles are shown in that mode.

**Note:** Currently, there is no option to hide subtitles in full-screen mode. To enable this functionality, we would need to design a solution for it or opt for a fully custom implementation by hiding the default AVPlayer control bar.

Demo Downloaded Video | Demo Streaming Video |
--- | --- |
<video src="https://github.com/user-attachments/assets/036d6d67-138c-4175-be73-1fc303f80d34" /> | <video src="https://github.com/user-attachments/assets/1113bf5a-0d42-42c0-91b4-babee20338f7" /> |

### CODE REVIEW

**Comment by saeedbashir** [comment]
@forgotvas It would be nice if you could also look as you did most of the work with videos.

**Comment by rnr** [comment]
Hello @shafqat-muneer 
On both videos you show in the PR description, the previously added subtitles (below the video) stop working (are not highlighted and do not auto-scroll) after exiting full screen mode. Could you please fix it. Thank you

**Comment by shafqat-muneer** [comment]
> Hello @shafqat-muneer On both videos you show in the PR description, the previously added subtitles (below the video) stop working (are not highlighted and do not auto-scroll) after exiting full screen mode. Could you please fix it. Thank you

Hi @rnr,
I was considering that auto-scrolling to the highlighted part might be intentionally disabled, as users may scroll up or down on their own to view previous or upcoming subtitles. If auto-scrolling is enabled, it could interrupt their navigation. I wanted to confirm if this is an intentional implementation. @saeedbashir or @forgotvas can confirm on it.

Once clarified, and if we decide to implement auto-scrolling to the highlighted content, I will handle it in a separate PR since it falls outside the scope of this one.

**Comment by rnr** [comment]
> > Hello @shafqat-muneer On both videos you show in the PR description, the previously added subtitles (below the video) stop working (are not highlighted and do not auto-scroll) after exiting full screen mode. Could you please fix it. Thank you
> 
> Hi @rnr, I was considering that auto-scrolling to the highlighted part might be intentionally disabled, as users may scroll up or down on their own to view previous or upcoming subtitles. If auto-scrolling is enabled, it could interrupt their navigation. I wanted to confirm if this is an intentional implementation. @saeedbashir or @forgotvas can confirm on it.
> 
> Once clarified, and if we decide to implement auto-scrolling to the highlighted content, I will handle it in a separate PR since it falls outside the scope of this one.

@shafqat-muneer  I'd like to point out that auto-scrolling now works in the 2U/develop branch (even after exiting fullscreen mode). Why did we decide to disable it? So other words it was working before this PR.

**Comment by shafqat-muneer** [comment]
> @shafqat-muneer I'd like to point out that auto-scrolling now works in the 2U/develop branch (even after exiting fullscreen mode). Why did we decide to disable it? So other words it was working before this PR.

@rnr It seems that the functionality may occasionally work, but not consistently. On the `2U/develop` branch, it’s currently not working on my end, whether in portrait or landscape mode. 😕 

Landscape | Portrait |
--- | --- |
<video src="https://github.com/user-attachments/assets/7c420b06-68e0-4562-828f-f384db93e60a" /> | <video src="https://github.com/user-attachments/assets/b0117bf0-5149-40fe-a015-637510632a2a" /> |

**Comment by rnr** [comment]
> > @shafqat-muneer I'd like to point out that auto-scrolling now works in the 2U/develop branch (even after exiting fullscreen mode). Why did we decide to disable it? So other words it was working before this PR.
> 
> @rnr It seems that the functionality may occasionally work, but not consistently. On the `2U/develop` branch, it’s currently not working on my end, whether in portrait or landscape mode. 😕
> 
> Landscape	Portrait
>  Landscape.mp4 
>  Portrait.mp4

I see what you mean - yes, it is broken when the user rewinds in fullscreen mode even in 2U/develop - I think we need to create a separate issue for this. Thank you.

**Review by forgotvas — APPROVED** [review]

**Review by rnr — APPROVED** [review]

**Review by saeedbashir — APPROVED** [review]
LGTM 👍

**Pull request merged**
