### PR TITLE
chore: highlight selected subtile - transcript

### PR DESCRIPTION
**Pull request by saeedbashir**
This PR address the issue `Videos > Transcripts are not highlighted while the video is playing`.

### CODE REVIEW

**Review by shafqat-muneer — APPROVED** [review]

**Comment by rnr** [comment]
@saeedbashir do you think it's highlighted enough for dark mode? (for light mode we have a bit different `textPrimary` and `textSecondary` but for dark they both are `white`)?

**Comment by saeedbashir** [comment]
Change the color and size of the highlighted transcript as per moiz feedback.

**Review by shafqat-muneer — APPROVED** [review]
LGTM

**Comment by saeedbashir** [comment]
@rnr Changes are approved by Moiz offline so I'm merging this so we can create the build for bug bash

**Pull request merged**
