### PR TITLE
feat: add notification project/framework for notification work

### PR DESCRIPTION
**Pull request by saeedbashir**
Add the `Notifications` project/framework in the project for all notification-related work, so moving to the plugin architecture will be easy as all the files will be in the Notification framework. 

 Note: Adding it before hand so everyone can add their work in the same framework.

### CODE REVIEW

**Comment by shafqat-muneer** [comment]
@saeedbashir Unit tests are failing. Please take a look.

**Comment by shafqat-muneer** [comment]
@saeedbashir Kindly update the script to assign the Notification sub-project team.

**Comment by saeedbashir** [comment]
> @saeedbashir Kindly update the script to assign the Notification sub-project team.

Done https://github.com/edx/edx-mobile-config/pull/187

**Review by rnr — APPROVED** [review]
LGTM!

**Review by shafqat-muneer — APPROVED** [review]
LGTM 👍

**Pull request merged**
