### PR TITLE
chore: update upgrade button and resume button style

### PR DESCRIPTION
**Pull request by saeedbashir**
Changing the color of the upgrade button to orange (button action color) and resume button style to secondary brand button as requested by Moiz.

https://2u-internal.atlassian.net/browse/LEARNER-10117

| light mode  | Dark Mode |
| ------------- | ------------- |
| LightMode | LightMode |

### CODE REVIEW

**Review by rnr — APPROVED** [review]

**Comment by rnr** [comment]
@saeedbashir tests look broken. please look on this. thank you

**Review by shafqat-muneer — APPROVED** [review]
LGTM 👍

**Comment by marcotuts** [comment]
I don't think this is a change we expect to merge in upstream, the resume / start course buttons should remain primary and the upgrade button placement is specific to the edX build.

**Comment by saeedbashir** [comment]
> I don't think this is a change we expect to merge in upstream, the resume / start course buttons should remain primary

@marcotuts I've made the resume button configurable in this PR https://github.com/edx/edx-mobile-marketplace-ios/pull/92. It will be primary for the openedX and edX(or any other provider) can configure it as per need.

> and the upgrade button placement is specific to the edX build

At the moment, yes the placement is edX specific, we have the plan to push the payment-related generic code (UI, config, parsing, etc) upstream, so for that do you or Sam have any mockup available with upgrade button on the course home screen?

**Pull request merged**
